ProxyURL = 'socks4://164.132.28.67:4145'
StartMsg = 'Hi! I want to help you to make wonderfull pictures!\n\nWe can stylize your images.\n\nPlease chose - use the existing style or your OWN STYLE\n(OWN styling takes about 10 minutes).'
WantTalkMsg1 = 'Good! Please send me an image of content. \nOr send /cancel if you don\'t want to.'
WantTalkMsg2 = 'Good! Please send me two images (content and style). \n First send me an image of context.\nOr send /cancel if you don\'t want to.'
CancelMsg = 'Bye! I hope we can talk again some day. \nBut if you change your mind, you can send me /start again for styling images.'
SndPict2Msg = 'Please, send me the second image (style)! \n'
WaitStylingMsg = 'Please, wait a little... \n'
WaitStylingMsg10min = 'Please, wait about 10 minutes\n'
NextActMsg = 'Wonderful!!! This is a styled picture!\nPlease, choose the next action!\nOr you can send /cancel if you don\'t want to.'

